export default {
  // App title
  app: {
    title: 'Extendustry',
  },
  
  // Menu
  menu: {
    file: 'File',
    saveProject: 'Save Extension Project',
    saveAs: 'Save As',
    openFromComputer: 'Open from Computer',
    exportAllBlocks: 'Export All Blocks',
    exportCurrentBlock: 'Export Current Block JSON',
    clearAllData: 'Clear All Data',
    newExtension: 'New Extension',
    exportExtension: 'Export Extension',
    projectSettings: 'Project Settings',
  },

// Project Settings
  projectSettings: {
    title: 'Project Settings',
    extensionName: 'Extension Name',
    extensionId: 'Extension ID',
    extensionAuthor: 'Author',
    extensionDescription: 'Description',
  },
  
  // Toolbar
  toolbar: {
    blockLibrary: 'Block Library',
    blockPreview: 'Block Preview',
    blockConfig: 'Block Config',
    functionConfig: 'Function Config',
  },
  
  // Block Library
  blockLibrary: {
    title: 'Block Library',
    noBlocks: 'No blocks yet',
    createNew: 'Create New Block',
    searchPlaceholder: 'Search blocks...',
    deleteConfirm: 'Are you sure you want to delete block "{{name}}"?',
    type: 'Type',
    elements: 'Elements',
    functions: 'Functions',
    moveUp: 'Move Up',
    moveDown: 'Move Down',
  },
  
  // Block Config
  blockConfig: {
    opcode: 'Opcode',
    opcodePlaceholder: 'e.g. my_custom_block',
    blockType: 'Block Type',
    branchCount: 'Branch Count',
    save: 'Save Block Style',
    blockInfo: 'Block Info',
    elementCount: 'Element Count',
    defaultBlockText: 'Default Block Text',
    types: {
      COMMAND: 'Command',
      REPORTER: 'Reporter',
      BOOLEAN: 'Boolean',
      EVENT: 'Event',
      HAT: 'Hat',
      LOOP: 'Loop',
      CONDITIONAL: 'Conditional',
    },
  },
  
  // Element Types
  elementTypes: {
    label: 'Label',
    text: 'Text',
    number: 'Number',
    dropdown: 'Dropdown',
    colour: 'Colour',
    boolean: 'Boolean',
    statement: 'Statement',
  },
  
  // Elements
  elements: {
    id: 'ID',
    text: 'Text',
    defaultValue: 'Default Value',
    options: 'Options',
    optionsPlaceholder: 'One option per line, format: Display Value,Value',
    noElements: 'No elements yet',
    addElement: 'Add Element',
    elementList: 'Element List',
  },
  
  // Validation Messages
  validation: {
    idRequired: 'ID cannot be empty',
    idInvalid: 'ID can only contain letters, numbers, and underscores',
    idDuplicate: 'ID already exists, please use a different name',
    idMustStartWithLetter: 'ID must start with a letter or underscore',
  },
  
// Function Config
  functionConfig: {
    editFunction: 'Edit Function',
    functionName: 'Function Name (opcode)',
    returnType: 'Return Type',
    parameters: 'Parameters',
    autoGenerated: '(Auto-generated from block elements)',
    functionCode: 'Function Code',
    codePlaceholder: '// Write your function code here...',
    saveFunction: 'Save Function',
    pleaseEnterName: 'Please enter function name',
    from: 'From',
    todoImplementLogic: '// TODO: Implement your logic here',
    returnTypes: {
      void: 'void',
      any: 'any',
      boolean: 'boolean',
      number: 'number',
      string: 'string',
    },
  },
  
// Messages
  messages: {
    blockSaved: 'Block saved!',
    projectSaved: 'Extension project saved',
    blockExported: 'Block JSON exported',
    unsavedChanges: 'Unsaved changes',
    unsavedChangesConfirm: 'Current block has unsaved changes. Create a new block? Unsaved changes will be lost.',
    unsavedChangesSwitchConfirm: 'Current block has unsaved changes. Switch blocks? Unsaved changes will be lost.',
    addElementTip: 'Use the toolbar on the right to add block elements',
    realtimePreview: 'Real-time preview of current block',
    importSuccess: 'Import successful!',
    importFailed: 'Import failed:',
    newExtensionConfirm: 'Are you sure you want to create a new extension? This will clear all blocks in the block library. This action cannot be undone.',
    newExtensionSuccess: 'New extension created, block library cleared',
    extensionExported: 'Extension exported',
    noBlocksToExport: 'No blocks to export, please create blocks first',
  },
  
  // Buttons
  buttons: {
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    add: 'Add',
    edit: 'Edit',
    duplicate: 'Duplicate',
    clearAll: 'Clear All',
  },
  
  // Dialogs
  dialogs: {
    importConfig: 'Import Config',
  },
};