export default {
  // 应用标题
  app: {
    title: 'Extendustry',
  },
  
  // 菜单
  menu: {
    file: '文件',
    saveProject: '保存扩展项目',
    saveAs: '另存为',
    openFromComputer: '从电脑中打开',
    exportAllBlocks: '导出所有积木',
    exportCurrentBlock: '导出当前积木 JSON',
    clearAllData: '清空所有数据',
    newExtension: '新建扩展',
    exportExtension: '导出扩展',
    projectSettings: '项目设定',
  },

// 项目设定
  projectSettings: {
    title: '项目设定',
    extensionName: '扩展名称',
    extensionId: '扩展ID',
    extensionAuthor: '作者',
    extensionLicense: '开源协议',
    extensionDescription: '描述',
    extensionColor: '扩展颜色',
    extensionIcon: '扩展图标',
    blockIcon: '积木图标',
    uploadIcon: '上传图标',
    removeIcon: '移除图标',
    noIcon: '无图标',
    extensionIconTip: '建议使用 48x48 像素的 PNG 图片，最大 100KB',
    blockIconTip: '建议使用 24x24 像素的 PNG 图片，最大 100KB',
    save: '保存',
    cancel: '取消',
    licenses: {
      mit: 'MIT License',
      apache: 'Apache 2.0',
      gpl: 'GPL-3.0',
      bsd: 'BSD-3-Clause',
      mpl: 'MPL-2.0',
      unlicense: 'Unlicense',
    },
  },
  
  // 工具栏
  toolbar: {
    blockLibrary: '积木库',
    blockPreview: '积木预览',
    blockConfig: '积木配置',
    functionConfig: '函数配置',
  },
  
  // 积木库
  blockLibrary: {
    title: '积木库',
    noBlocks: '暂无积木',
    createNew: '创建新积木',
    searchPlaceholder: '搜索积木...',
    deleteConfirm: '确定要删除积木 "{{name}}" 吗？',
    type: '类型',
    elements: '元素',
    functions: '函数',
    moveUp: '向上移动',
    moveDown: '向下移动',
  },
  
  // 积木配置
  blockConfig: {
    opcode: '操作码 (opcode)',
    opcodePlaceholder: '例如: my_custom_block',
    blockType: '积木类型',
    branchCount: '分支数量',
    save: '保存积木样式',
    blockInfo: '积木信息',
    elementCount: '元素数量',
    defaultBlockText: '默认积木文本',
    types: {
      COMMAND: '命令积木',
      REPORTER: '报告积木',
      BOOLEAN: '布尔积木',
      EVENT: '事件积木',
      HAT: '帽子积木',
      LOOP: '循环积木',
      CONDITIONAL: '分支积木',
    },
  },
  
  // 元素类型
  elementTypes: {
    label: '标签',
    text: '文本',
    number: '数字',
    dropdown: '下拉菜单',
    colour: '颜色',
    boolean: '布尔值',
    statement: '分支',
  },
  
  // 元素编辑
  elements: {
    id: 'ID',
    text: '文本',
    defaultValue: '默认值',
    options: '选项',
    optionsPlaceholder: '每行一个选项，格式：显示值,值',
    noElements: '暂无元素',
    addElement: '添加元素',
    elementList: '元素列表',
  },
  
  // 验证提示
  validation: {
    idRequired: 'ID不能为空',
    idInvalid: 'ID只能包含字母、数字和下划线',
    idDuplicate: 'ID已存在，请使用不同的名称',
    idMustStartWithLetter: 'ID必须以字母或下划线开头',
  },
  
  // 函数配置
  functionConfig: {
    editFunction: '编辑函数',
    functionName: '函数名称 (opcode)',
    returnType: '返回类型',
    parameters: '参数',
    autoGenerated: '(自动生成自积木元素)',
    functionCode: '函数代码',
    codePlaceholder: '// 在这里编写你的函数代码...',
    saveFunction: '保存函数',
    pleaseEnterName: '请输入函数名称',
    from: '来自',
    todoImplementLogic: '// TODO: 在这里实现你的逻辑',
    returnTypes: {
      void: 'void',
      any: 'any',
      boolean: 'boolean',
      number: 'number',
      string: 'string',
    },
  },
  
  // 提示消息
  messages: {
    blockSaved: '积木已保存！',
    projectSaved: '扩展项目已保存',
    settingsSaved: '项目设定已保存',
    blockExported: '积木 JSON 已导出',
    unsavedChanges: '未保存的更改',
    unsavedChangesConfirm: '当前积木有未保存的更改，确定要创建新积木吗？未保存的更改将丢失。',
    unsavedChangesSwitchConfirm: '当前积木有未保存的更改，确定要切换吗？未保存的更改将丢失。',
    addElementTip: '使用右侧工具栏添加积木元素',
    realtimePreview: '当前积木的实时预览',
    importSuccess: '导入成功！',
    importFailed: '导入失败：',
    newExtensionConfirm: '确定要新建扩展吗？这将清空积木库中的所有积木，此操作不可恢复。',
    newExtensionSuccess: '已新建扩展，积木库已清空',
    extensionExported: '扩展已导出',
    noBlocksToExport: '没有积木可以导出，请先创建积木',
  },
  
// 按钮
  buttons: {
    language: '语言',
    save: '保存',
    delete: '删除',
    cancel: '取消',
    confirm: '确定',
    add: '添加',
    clearAll: '清空全部',
  },
  
// 对话框
  dialogs: {
    importConfig: '导入配置',
  },
};