import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useLanguage } from '../contexts/LanguageContext';
import { useAlert } from './Alert';
import Editor from '@monaco-editor/react';
import {
  Box,
  Typography,
  Paper,
  TextField,
  Button,
  Stack,
  Select,
  MenuItem,
  Chip,
  IconButton,
  Divider,
  Alert,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Tooltip
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import DeleteIcon from '@mui/icons-material/Delete';
import AddIcon from '@mui/icons-material/Add';
import CodeIcon from '@mui/icons-material/Code';

function FunctionConfig({ blockElements, blockType, blockOpcode, functions, onSave, darkMode }) {
  const { showWarning } = useAlert();
  const { t } = useLanguage();
  const [currentFunction, setCurrentFunction] = useState({
    id: null,
    name: '',
    returnType: 'void',
    code: '',
    parameters: []
  });
  const initializedRef = useRef(false);

  // 初始化函数
  useEffect(() => {
    // 如果有已保存的函数，使用它
    if (functions && functions.length > 0) {
      const savedFunction = functions[0];
      const currentParams = generateParameters();
      
      // 保留已保存函数中的 constName
      const savedParamMap = new Map(savedFunction.parameters.map(p => [p.elementId, p]));
      currentParams.forEach(p => {
        const savedParam = savedParamMap.get(p.elementId);
        if (savedParam && savedParam.constName) {
          p.constName = savedParam.constName;
        }
      });
      
      // 检查参数是否发生变化
      const paramsChanged = JSON.stringify(savedFunction.parameters) !== JSON.stringify(currentParams);
      
      if (paramsChanged) {
        // 参数变化，智能更新函数代码
        const updatedCode = updateFunctionWithNewParams(
          savedFunction.code,
          savedFunction.parameters,
          currentParams
        );
        
        setCurrentFunction({
          ...savedFunction,
          code: updatedCode,
          parameters: currentParams
        });
      } else if (!initializedRef.current) {
        // 参数未变化且未初始化，直接使用已保存的函数
        setCurrentFunction(savedFunction);
      }
    } else if (!initializedRef.current) {
      // 没有已保存的函数且未初始化，生成默认函数
      const defaultParams = generateParameters();
      const returnType = blockType === 'REPORTER' ? 'any' : blockType === 'BOOLEAN' ? 'boolean' : 'void';
      const funcName = blockOpcode || 'customFunction';
      
      setCurrentFunction({
        id: null,
        name: funcName,
        returnType: returnType,
        code: generateDefaultCode(funcName, returnType, defaultParams),
        parameters: defaultParams,
        autoGenerated: true
      });
    }
    
    initializedRef.current = true;
  }, []); // 只在组件挂载时执行一次

  // 生成默认函数代码
  const generateDefaultCode = (funcName, returnType, params) => {
    const paramList = params.map(p => `${p.name}`).join(', ');
    
    let code = `function ${funcName}(${paramList}) {\n`;
    
    // 为每个参数生成 const 声明，使用 input_ 前缀
    params.forEach(p => {
      const constName = `input_${p.constName || p.name}`;
      code += `  const ${constName} = ${p.name};\n`;
    });
    
    code += `  ${t('functionConfig.todoImplementLogic', { defaultValue: '// TODO: Implement your logic here' })}\n`;
    
    if (params.length > 0) {
      const constNames = params.map(p => `input_${p.constName || p.name}`);
      code += `  console.log(${constNames.join(', ')});\n`;
    }
    
    code += `}\n`;
    
    return code;
  };

  // 智能更新函数代码，添加新的参数定义而不改变其他代码
  const updateFunctionWithNewParams = (currentCode, oldParams, newParams) => {
    // 找到函数定义行
    const lines = currentCode.split('\n');
    let functionStartLine = -1;
    let functionEndLine = -1;
    let braceCount = 0;
    let functionStart = -1;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      
      // 查找 function 定义
      if (functionStart === -1 && line.match(/^\s*function\s+\w+\s*\(/)) {
        functionStart = i;
        functionStartLine = i;
      }
      
      if (functionStart !== -1) {
        braceCount += (line.match(/{/g) || []).length;
        braceCount -= (line.match(/}/g) || []).length;
        
        if (braceCount === 0 && functionStartLine !== -1) {
          functionEndLine = i;
          break;
        }
      }
    }

    if (functionStartLine === -1 || functionEndLine === -1) {
      // 无法解析函数，返回原代码
      return currentCode;
    }

    // 提取函数签名
    const functionLine = lines[functionStartLine];
    const functionMatch = functionLine.match(/function\s+(\w+)\s*\(([^)]*)\)/);
    
    if (!functionMatch) {
      return currentCode;
    }

    const funcName = functionMatch[1];
    const paramList = newParams.map(p => `${p.name}`).join(', ');
    
    // 构建新的函数签名
    lines[functionStartLine] = `function ${funcName}(${paramList}) {`;

    // 找到 const input_ 定义的结束位置
    let lastConstLine = functionStartLine;
    const constLines = {}; // 记录 const 行：constName（不带前缀）-> lineIndex
    for (let i = functionStartLine + 1; i <= functionEndLine; i++) {
      const line = lines[i];
      // 检查是否是 const input_ 行
      const match = line.match(/^\s*const\s+input_(\w+)\s*=/);
      if (match) {
        constLines[match[1]] = i;
        lastConstLine = i;
      } else if (line.trim() && !line.match(/^\s*\/\//)) {
        // 遇到非注释、非 const 的代码行，停止
        break;
      }
    }

    // 创建参数映射：elementId -> param
    const newParamMap = new Map(newParams.map(p => [p.elementId, p]));
    const oldParamMap = new Map(oldParams.map(p => [p.elementId, p]));

    // 找出需要删除、修改和新增的参数
    const toDelete = [];
    const toUpdate = [];
    const toAdd = [];

    // 检查旧参数
    oldParamMap.forEach((param, elementId) => {
      if (!newParamMap.has(elementId)) {
        // 参数被删除
        toDelete.push(elementId);
      } else {
        // 参数存在，检查是否需要更新赋值
        const newParam = newParamMap.get(elementId);
        if (newParam.name !== param.name) {
          // 参数名变化，需要更新赋值，但保持 constName 不变
          toUpdate.push({ 
            elementId, 
            constName: param.constName || param.name,
            oldName: param.name, 
            newName: newParam.name 
          });
        }
      }
    });

    // 检查新参数
    newParamMap.forEach((param, elementId) => {
      if (!oldParamMap.has(elementId)) {
        // 新增参数
        toAdd.push(param);
      }
    });

    // 删除旧的 const 定义（从后往前删除，避免索引变化）
    toDelete.sort((a, b) => {
      const constNameA = oldParamMap.get(a)?.constName || oldParamMap.get(a)?.name;
      const constNameB = oldParamMap.get(b)?.constName || oldParamMap.get(b)?.name;
      return (constLines[constNameB] || -1) - (constLines[constNameA] || -1);
    });
    toDelete.forEach(elementId => {
      const oldParam = oldParamMap.get(elementId);
      const constName = oldParam?.constName || oldParam?.name;
      if (constLines[constName] !== undefined) {
        lines.splice(constLines[constName], 1);
      }
    });

    // 更新现有 const 的赋值
    toUpdate.forEach(({ constName, oldName, newName }) => {
      const lineIndex = constLines[constName];
      if (lineIndex !== undefined) {
        // 更新赋值：const input_xxx = oldName; -> const input_xxx = newName;
        lines[lineIndex] = lines[lineIndex].replace(
          /=\s*\w+\s*;/,
          `= ${newName};`
        );
      }
    });

    // 添加新的 const 定义
    const newConstLines = [];
    toAdd.forEach(p => {
      const constName = `input_${p.constName || p.name}`;
      newConstLines.push(`  const ${constName} = ${p.name};`);
    });

    // 在 const 定义区域后添加新的 const 定义
    if (newConstLines.length > 0) {
      // 重新计算 lastConstLine（因为可能删除了一些行）
      let actualLastConstLine = functionStartLine;
      for (let i = functionStartLine + 1; i < lines.length; i++) {
        const line = lines[i];
        const match = line.match(/^\s*const\s+input_\w+\s*=/);
        if (match) {
          actualLastConstLine = i;
        } else if (line.trim() && !line.match(/^\s*\/\//)) {
          break;
        }
      }
      lines.splice(actualLastConstLine + 1, 0, ...newConstLines);
    }

    return lines.join('\n');
  };

  // 自动生成参数列表
  const generateParameters = () => {
    const params = [];
    
    blockElements.forEach((element, index) => {
      // 参数名使用元素 id
      let paramType = 'any';
      
      switch (element.type) {
        case 'text':
          paramType = 'string';
          break;
        case 'number':
          paramType = 'number';
          break;
        case 'boolean':
          paramType = 'boolean';
          break;
        case 'colour':
          paramType = 'string';
          break;
        case 'dropdown':
          paramType = 'string';
          break;
        default:
          // label 和 statement 类型不生成参数
          return;
      }
      
      params.push({
        name: element.name,
        type: paramType,
        elementId: element.id,
        elementType: element.type,
        constName: element.name,  // 使用当前参数名作为常量名
        autoGenerated: true
      });
    });
    
    return params;
  };

  // 创建新函数
  const createNewFunction = () => {
    const params = generateParameters();
    const returnType = blockType === 'REPORTER' ? 'any' : blockType === 'BOOLEAN' ? 'boolean' : 'void';
    const funcName = blockOpcode || 'customFunction';
    
    setCurrentFunction({
      id: null,
      name: funcName,
      returnType: returnType,
      code: generateDefaultCode(funcName, returnType, params),
      parameters: params,
      autoGenerated: true
    });
  };

  // 保存当前函数
  const saveCurrentFunction = () => {
    if (!currentFunction.name.trim()) {
      showWarning(t('functionConfig.pleaseEnterName'));
      return;
    }

    // 通知父组件
    if (onSave) {
      onSave([currentFunction]);
    }
  };

  // 添加参数
  const addParameter = () => {
    setCurrentFunction({
      ...currentFunction,
      parameters: [...currentFunction.parameters, { name: '', type: 'string' }]
    });
  };

  // 更新参数
  const updateParameter = (index, field, value) => {
    const newParams = [...currentFunction.parameters];
    newParams[index][field] = value;
    setCurrentFunction({
      ...currentFunction,
      parameters: newParams
    });
  };

  // 删除参数
  const removeParameter = (index) => {
    const newParams = currentFunction.parameters.filter((_, i) => i !== index);
    setCurrentFunction({
      ...currentFunction,
      parameters: newParams
    });
  };

  // 更新当前函数代码时自动更新参数
  const handleCodeChange = useCallback((newCode) => {
    setCurrentFunction(prev => ({
      ...prev,
      code: newCode
    }));
  }, []);

  const getReturnTypeColor = (type) => {
    const colors = {
      'void': '#6366f1',
      'any': '#667eea',
      'boolean': '#f59f00',
      'number': '#11998e',
      'string': '#00c6ff'
    };
    return colors[type] || '#666';
  };

  return (
    <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      {/* 函数编辑器 */}
      {currentFunction.name && (
        <Paper elevation={1} sx={{ flex: 1, p: 2, bgcolor: 'background.paper', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
          <Typography variant="h6" gutterBottom color="text.primary">
            {t('functionConfig.editFunction')}
          </Typography>

          <Stack spacing={2} sx={{ flex: 1, overflowY: 'auto' }}>
            {/* 函数信息 */}
            <Box>
              <Typography variant="body2" gutterBottom color="text.secondary">
                {t('functionConfig.functionName')}
              </Typography>
              <TextField
                value={currentFunction.name}
                fullWidth
                size="small"
                disabled
                sx={{ 
                  '& .MuiInputBase-root.Mui-disabled': {
                    bgcolor: 'action.disabledBackground'
                  }
                }}
              />
            </Box>

            {/* 返回类型 */}
            <Box>
              <Typography variant="body2" gutterBottom color="text.secondary">
                {t('functionConfig.returnType')}
              </Typography>
              <Typography variant="body1" color="text.primary" sx={{ fontWeight: 500 }}>
                {currentFunction.returnType} 
              </Typography>
            </Box>

            {/* 参数列表 */}
            <Accordion>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                <Typography variant="body2">
                  {t('functionConfig.parameters')} ({currentFunction.parameters.length})
                  {currentFunction.autoGenerated && (
                    <Typography 
                      variant="caption" 
                      sx={{ ml: 1, color: 'primary.main', fontStyle: 'italic' }}
                    >
                      {t('functionConfig.autoGenerated')}
                    </Typography>
                  )}
                </Typography>
              </AccordionSummary>
              <AccordionDetails>
                <Stack spacing={1}>
                  {currentFunction.parameters.map((param, index) => (
                    <Box key={index} sx={{ display: 'flex', gap: 1, alignItems: 'center', bgcolor: 'background.default', p: 1, borderRadius: 1 }}>
                      <Typography 
                        variant="caption" 
                        sx={{ 
                          minWidth: 80, 
                          color: 'text.secondary',
                          fontWeight: 'bold'
                        }}
                      >
                        {t('functionConfig.from')}: {t(`elementTypes.${param.elementType}`)}
                      </Typography>
                      <TextField
                        placeholder={t('elements.id')}
                        value={param.name}
                        size="small"
                        sx={{ flex: 1 }}
                        disabled
                      />
                      <Select
                        value={param.type}
                        size="small"
                        sx={{ width: 100 }}
                        disabled
                      >
                        <MenuItem value="string">string</MenuItem>
                        <MenuItem value="number">number</MenuItem>
                        <MenuItem value="boolean">boolean</MenuItem>
                        <MenuItem value="any">any</MenuItem>
                      </Select>
                    </Box>
                  ))}
                </Stack>
              </AccordionDetails>
            </Accordion>

            {/* 代码编辑器 */}
            <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', minHeight: 300 }}>
              <Typography variant="body2" gutterBottom color="text.secondary">
                {t('functionConfig.functionCode')}
              </Typography>
              <Box sx={{ flex: 1, border: '1px solid #e0e0e0', borderRadius: 1, overflow: 'hidden', borderColor: darkMode ? '#333' : '#e0e0e0' }}>
                <Editor
                  key={darkMode ? 'dark' : 'light'}
                  height="100%"
                  defaultLanguage="javascript"
                  value={currentFunction.code}
                  onChange={(value) => handleCodeChange(value || '')}
                  theme={darkMode ? 'vs-dark' : 'vs-light'}
                  options={{
                    minimap: { enabled: true },
                    fontSize: 13,
                    lineNumbers: 'on',
                    roundedSelection: false,
                    scrollBeyondLastLine: false,
                    automaticLayout: true,
                    tabSize: 2,
                    wordWrap: 'on',
                    formatOnPaste: true,
                    formatOnType: true,
                    suggestOnTriggerCharacters: true,
                  }}
                />
              </Box>
            </Box>

            {/* 保存按钮 */}
            <Box sx={{ display: 'flex', justifyContent: 'flex-end', pt: 1 }}>
              <Button
                variant="contained"
                onClick={saveCurrentFunction}
              >
                {t('functionConfig.saveFunction')}
              </Button>
            </Box>
          </Stack>
        </Paper>
      )}
    </Box>
  );
}

export default FunctionConfig;