import React, { useState, useEffect } from 'react';
import { useAlert } from './Alert';
import {
  Box,
  Typography,
  Paper,
  TextField,
  Button,
  Stack,
  Select,
  MenuItem,
  Chip,
  IconButton,
  Divider,
  Alert,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Tooltip
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import DeleteIcon from '@mui/icons-material/Delete';
import AddIcon from '@mui/icons-material/Add';
import CodeIcon from '@mui/icons-material/Code';

function FunctionConfig({ blockElements, blockType, blockOpcode, onSave }) {
  const { showWarning } = useAlert();
  const [currentFunction, setCurrentFunction] = useState({
    id: null,
    name: '',
    returnType: 'void',
    code: '',
    parameters: []
  });

  // 初始化函数
  useEffect(() => {
    const defaultParams = generateParameters();
    const returnType = blockType === 'REPORTER' ? 'any' : blockType === 'BOOLEAN' ? 'boolean' : 'void';
    const funcName = blockOpcode || 'customFunction';
    
    setCurrentFunction({
      id: null,
      name: funcName,
      returnType: returnType,
      code: generateDefaultCode(funcName, returnType, defaultParams),
      parameters: defaultParams,
      autoGenerated: true
    });
  }, [blockElements, blockType, blockOpcode]);

  // 生成默认函数代码
  const generateDefaultCode = (funcName, returnType, params) => {
    const paramList = params.map(p => `${p.type} ${p.name}`).join(', ');
    
    let code = `// ${funcName}\n`;
    code += `// 参数说明：\n`;
    params.forEach(p => {
      code += `//   ${p.name}: ${p.type} - ${p.elementType}类型的输入\n`;
    });
    code += `\n`;
    
    if (returnType === 'void') {
      code += `function ${funcName}(${paramList}) {\n`;
      code += `  // TODO: 在这里实现你的逻辑\n`;
      if (params.length > 0) {
        code += `  console.log('${funcName} 被调用', { ${params.map(p => `${p.name}`).join(', ')} });\n`;
      } else {
        code += `  console.log('${funcName} 被调用');\n`;
      }
      code += `  \n`;
      code += `  // 你的代码...\n`;
      code += `}\n`;
    } else {
      code += `function ${funcName}(${paramList}) {\n`;
      code += `  // TODO: 在这里实现你的逻辑\n`;
      if (params.length > 0) {
        code += `  console.log('${funcName} 被调用', { ${params.map(p => `${p.name}`).join(', ')} });\n`;
      } else {
        code += `  console.log('${funcName} 被调用');\n`;
      }
      code += `  \n`;
      code += `  // 你的代码...\n`;
      code += `  \n`;
      
      let defaultValue;
      switch (returnType) {
        case 'boolean':
          defaultValue = 'true';
          break;
        case 'number':
          defaultValue = '0';
          break;
        case 'string':
          defaultValue = '""';
          break;
        default:
          defaultValue = 'null';
      }
      code += `  return ${defaultValue}; // 返回 ${returnType} 类型的值\n`;
      code += `}\n`;
    }
    
    return code;
  };

  // 自动生成参数列表
  const generateParameters = () => {
    const params = [];
    
    blockElements.forEach((element, index) => {
      // 参数名使用元素 id
      let paramType = 'any';
      
      switch (element.type) {
        case 'text':
          paramType = 'string';
          break;
        case 'number':
          paramType = 'number';
          break;
        case 'boolean':
          paramType = 'boolean';
          break;
        case 'colour':
          paramType = 'string';
          break;
        case 'dropdown':
          paramType = 'string';
          break;
        default:
          // label 和 statement 类型不生成参数
          return;
      }
      
      params.push({
        name: element.name,
        type: paramType,
        elementId: element.id,
        elementType: element.type,
        autoGenerated: true
      });
    });
    
    return params;
  };

  // 创建新函数
  const createNewFunction = () => {
    const params = generateParameters();
    const returnType = blockType === 'REPORTER' ? 'any' : blockType === 'BOOLEAN' ? 'boolean' : 'void';
    const funcName = blockOpcode || 'customFunction';
    
    setCurrentFunction({
      id: null,
      name: funcName,
      returnType: returnType,
      code: generateDefaultCode(funcName, returnType, params),
      parameters: params,
      autoGenerated: true
    });
  };

  // 保存当前函数
  const saveCurrentFunction = () => {
    if (!currentFunction.name.trim()) {
      showWarning('请输入函数名称');
      return;
    }

    // 通知父组件
    if (onSave) {
      onSave([currentFunction]);
    }
  };

  // 添加参数
  const addParameter = () => {
    setCurrentFunction({
      ...currentFunction,
      parameters: [...currentFunction.parameters, { name: '', type: 'string' }]
    });
  };

  // 更新参数
  const updateParameter = (index, field, value) => {
    const newParams = [...currentFunction.parameters];
    newParams[index][field] = value;
    setCurrentFunction({
      ...currentFunction,
      parameters: newParams
    });
  };

  // 删除参数
  const removeParameter = (index) => {
    const newParams = currentFunction.parameters.filter((_, i) => i !== index);
    setCurrentFunction({
      ...currentFunction,
      parameters: newParams
    });
  };

  // 更新当前函数代码时自动更新参数
  const handleCodeChange = (newCode) => {
    setCurrentFunction({
      ...currentFunction,
      code: newCode
    });
  };

  const getReturnTypeColor = (type) => {
    const colors = {
      'void': '#6366f1',
      'any': '#667eea',
      'boolean': '#f59f00',
      'number': '#11998e',
      'string': '#00c6ff'
    };
    return colors[type] || '#666';
  };

  return (
    <Box sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      {/* 函数编辑器 */}
      {currentFunction.name && (
        <Paper elevation={1} sx={{ flex: 1, p: 2, bgcolor: 'background.paper', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
          <Typography variant="h6" gutterBottom color="text.primary">
            编辑函数
          </Typography>

          <Stack spacing={2} sx={{ flex: 1, overflowY: 'auto' }}>
            {/* 函数信息 */}
            <Box>
              <Typography variant="body2" gutterBottom color="text.secondary">
                函数名称 (opcode)
              </Typography>
              <TextField
                value={currentFunction.name}
                fullWidth
                size="small"
                disabled
                sx={{ 
                  '& .MuiInputBase-root.Mui-disabled': {
                    bgcolor: 'action.disabledBackground'
                  }
                }}
              />
            </Box>

            {/* 返回类型 */}
            <Box>
              <Typography variant="body2" gutterBottom color="text.secondary">
                返回类型
              </Typography>
              <Typography variant="body1" color="text.primary" sx={{ fontWeight: 500 }}>
                {currentFunction.returnType} 
              </Typography>
            </Box>

            {/* 参数列表 */}
            <Accordion>
              <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                <Typography variant="body2">
                  参数 ({currentFunction.parameters.length})
                  {currentFunction.autoGenerated && (
                    <Typography 
                      variant="caption" 
                      sx={{ ml: 1, color: 'primary.main', fontStyle: 'italic' }}
                    >
                      (自动生成自积木元素)
                    </Typography>
                  )}
                </Typography>
              </AccordionSummary>
              <AccordionDetails>
                <Stack spacing={1}>
                  {currentFunction.parameters.map((param, index) => (
                    <Box key={index} sx={{ display: 'flex', gap: 1, alignItems: 'center', bgcolor: 'background.default', p: 1, borderRadius: 1 }}>
                      <Typography 
                        variant="caption" 
                        sx={{ 
                          minWidth: 80, 
                          color: 'text.secondary',
                          fontWeight: 'bold'
                        }}
                      >
                        来自: {param.elementType}
                      </Typography>
                      <TextField
                        placeholder="参数名"
                        value={param.name}
                        size="small"
                        sx={{ flex: 1 }}
                        disabled
                      />
                      <Select
                        value={param.type}
                        size="small"
                        sx={{ width: 100 }}
                        disabled
                      >
                        <MenuItem value="string">string</MenuItem>
                        <MenuItem value="number">number</MenuItem>
                        <MenuItem value="boolean">boolean</MenuItem>
                        <MenuItem value="any">any</MenuItem>
                      </Select>
                    </Box>
                  ))}
                </Stack>
              </AccordionDetails>
            </Accordion>

            {/* 代码编辑器 */}
            <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
              <Typography variant="body2" gutterBottom color="text.secondary">
                函数代码
              </Typography>
              <TextField
                multiline
                fullWidth
                value={currentFunction.code}
                onChange={(e) => handleCodeChange(e.target.value)}
                rows={10}
                sx={{
                  flex: 1,
                  '& .MuiInputBase-root': {
                    fontFamily: 'monospace',
                    fontSize: '13px',
                    lineHeight: 1.6,
                  },
                  '& .MuiOutlinedInput-root': {
                    height: '100%',
                    alignItems: 'flex-start',
                  },
                }}
                placeholder="// 在这里编写你的函数代码..."
              />
            </Box>

            {/* 保存按钮 */}
            <Box sx={{ display: 'flex', justifyContent: 'flex-end', pt: 1 }}>
              <Button
                variant="contained"
                onClick={saveCurrentFunction}
              >
                保存函数
              </Button>
            </Box>
          </Stack>
        </Paper>
      )}
    </Box>
  );
}

export default FunctionConfig;